### ISSUE TITLE
Polyfill和Shim

### ISSUE THREAD

**Issue by CodecWang** [CodecWang/main-site#1]
http://codec.wang/#/posts/polyfill-and-shim 

 Description

**Comment by mengki258** [comment]
大佬的opencv教学太niceee了🥰

**Comment by chenwg3017** [comment]
# 感谢 #

**Comment by zhj-666** [comment]
蓝色的HSV值的上下限lower和upper范围，如何根据[[[120 255 255]]]，算出lower_blue = np.array([100, 110, 110])
upper_blue = np.array([130, 255, 255])

**Comment by keaneLai** [comment]
真不错

**Comment by lushuangning** [comment]
针不戳，谢谢

**Comment by lushuangning** [comment]
python opencv 3.4.3.18以上版本，findContours()只返回两个参数，不再返回原来的二值化图片了

**Comment by takuzenlu** [comment]
真的很好，就是不知道什么时候更新进阶篇或者实战篇之类的，期待！！！

**Comment by ZoroWang** [comment]
番外没了

**Comment by ZoroWang** [comment]
图像总像素数应该是width*height吧，如果再乘上通道数（如果一个通道占8bit的话），是不是变成总字节数了

**Comment by Lophyads** [comment]
求解答： 如果滑动条调节Canny检测阈值分割后的图像的边缘的高低阈值，会发现无论怎么调，图像边缘都不变
```
img1 = cv2.imread('sudoku.jpg', 0)
_, th1 = cv2.threshold(img1, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.namedWindow('check')
cv2.createTrackbar('Min_val', 'check', 0, 255, nothing)
cv2.createTrackbar('Max_val', 'check', 0, 255, nothing)
while True:
    lower = cv2.getTrackbarPos('Min_val', 'check')
    upper = cv2.getTrackbarPos('Max_val', 'check')
    edges2 = cv2.Canny(th1, lower, upper)
   #edges2 = cv2.Canny(img1,lower, upper) 则可以
    cv2.imshow('check', np.hstack((img1, edges2)))
    if cv2.waitKey(1) == 27:
        break
```

**Comment by LinJ0866** [comment]
thresh_trunc，thresh_tozero和thresh_tozero_inv的公式感觉不大对

**Comment by LinJ0866** [comment]
> @ZoroWang
> 番外没了

番外的链接有问题，可以从目录进番外

**Comment by hyper-z** [comment]
大佬你的博客用什么框架搭建的啊

**Comment by CodecWang** [comment]
docsify，使用挺简单的，可以试试～

2021年12月6日 下午12:07，hyper-z ***@***.******@***.***>> 写道：



大佬你的博客用什么框架搭建的啊

**Comment by CheshireCC** [comment]
我有lena的原图哦，嘿嘿~嘿嘿

**Comment by much0762** [comment]
摄像头的ID有时候不为0，需要自己查找
```python
ID = 0 #700
capture = cv2.VideoCapture(ID)

while(True):
    ret, frame = capture.read()
    if ret == True:
        print(ID)
        break
    ID+=1
    capture = cv2.VideoCapture(ID)
```

**Comment by Alkaidcc** [comment]
[Otsu算法详解](http://codec.wang/#/opencv/start/extra-04-otsu-thresholding?id=otsu%e7%ae%97%e6%b3%95%e8%af%a6%e8%a7%a3)图片上的μ0应该为2，μ1应该为0
